### ISSUE TITLE
Clarification of use-case

### ISSUE THREAD

**Issue by plektral** [leotaku/fi-emacs#3]
I just stumbled upon this project, and I would like to understand better how this system would be employed in practice and what its advantages are compared to more traditional approaches. I currently have a modularized configuration that is byte-compiled and built with eldev, and use straight.el along with use-package to manage my packages. If it's not too difficult to explain, how would a system based around fi-emacs compare to the sort of system I use?

**Comment by leotaku** [comment]
Right, so fi-emacs really is a collection of various things that I use to structure my configuration. There's `fi.el` which is just miscellaneous utility functions, `eu.el` which is just a keybinding macro. Then the more interesting parts of the projects are `bk.el` which is a use-package-like configuration system and `sd.el` which is the lower-level dependency management code `bk.el` is built on.

You could absolutely keep using eldev to byte-compile your configuration and straight for package-management. You would however want to replace all `use-package` invocations with `bk-block`, migrate any keywords that are not supported by `bk-block`, and add explicit dependencies to your `bk-block` statements. You can look at [my personal configuration](https://github.com/leotaku/.emacs.d/blob/master/init.el) to figure out how this works.

In abstract terms, the main idea behind the whole system is transparency. I hated that with use-package and similar systems, a change in your configuration or update to a package could silently break your setup and only appear when the related configuration block gets auto-loaded. With `bk.el` there is deliberately no support for auto-loading, and every time something breaks you will get an exact backtrace showing where something went wrong. (e.g. *a* failed because its dependency *b* failed because of the following error). 

I imagine this would be off-putting to people who care about their Emacs startup time, but I personally really don't care because I use Emacs in daemon mode anyways. The project used to have an "async" way of loading all packages during idle time directly after startup, which was conceptually interesting and lead to very fast restarts, but I removed that when I stopped caring about my Emacs startup time. 

I also imagine that, if you did care about startup time, you could quite easily use fi-emacs utilities to produce and use a consistent dump image.

<hr>

What is most important to understand is that `fi-emacs` is based purely on how I personally like my Emacs setup to behave. If you do not share my "taste" very closely, you probably won't enjoy it at all.

**Comment by plektral** [comment]
@leotaku Sorry for the late response! That clarifies things. I do currently care about startup time, but I appreciate the transparency of you approach. You've raised a downside of autoloading that I hadn't considered. I may experiment with this to achieve what you suggested - using fi-emacs to produce and use a consistent dump image. 

Thanks for the detailed response and suggestions!
